{pkgs}:

pkgs.python311.withPackages (ps: [
    #ps.setuptools
    ps.greenlet
    ps.gevent
    ps.psycopg2
    
    ps.pillow
    ps.lxml
    ps.babel
    ps.chardet
    ps.cryptography
    ps.decorator
    ps.docutils
    ps.freezegun
    ps.idna
    ps.jinja2
    ps.libsass
    ps.markupsafe
    ps.num2words
    ps.ofxparse
    ps.passlib
    ps.polib
    ps.psutil
    ps.pydot
    ps.pyopenssl
    ps.pypdf2
    ps.pyserial
    ps.python-dateutil
    ps.python-stdnum
    ps.pytz
    ps.pyusb
    ps.qrcode
    ps.requests
    ps.urllib3
    ps.vobject
    ps.werkzeug
    ps.xlsxwriter
    ps.rjsmin
    ps.geoip2
    ps.python-ldap
    ps.xlwt
    ps.mock
    ps.zeep
    ps.ebaysdk
    ps.reportlab
    ps.xlrd
    ps.python-barcode
    ps.numpy
    ps.pandas
    ps.openpyxl
])

