#!./python310

# set server timezone in UTC before time module imported
__import__('os').environ['TZ'] = 'UTC'

import odoo

import sys

print("python:", sys. version)

from importlib import metadata
for pkg in ['werkzeug','reportlab', 'pypdf2', 'pillow', 'xlrd', 'zeep', 'gevent', 'psycopg2','freezegun','greenlet','jinja2','libsass','lxml','markupsafe','urllib3','vobject','xlwt','pydot','pyopenssl','python-ldap','pytz','qrcode','requests','rjsmin','XlsxWriter']: print(pkg, ':', metadata.version(pkg))

#https://github.com/microsoft/debugpy/issues/1206

if __name__ == "__main__":
    odoo.cli.main()
